version: '3'
services:
  db:
    container_name: taskmanager_db
    image: postgres:12
    restart: always
    environment:
      - POSTGRES_PASSWORD=asdf
      # creates the superuser and a db with the same name.
      # defaults to postgres.
      - POSTGRES_USER=postgres
      # defaults to the value of user.
      - POSTGRES_DB=taskmanager
    ports:
      - '5432:5432'
# try this out with:
# psql -U postgres -h localhost -p 5432 <database>
